name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        java-version:
          - 17
          - 18
          - 19
          - 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Build
        run: mvn --batch-mode --update-snapshots clean verify
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: target/jacoco-report
